###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - lumen
  postgres:
    image: postgres:11.1-alpine
    container_name: lumen-postgres
    working_dir: /application
    volumes:
      - .:/application
    environment:
      - POSTGRES_USER=lumen
      - POSTGRES_PASSWORD=lumen
      - POSTGRES_DB=lumen
    ports:
      - "5432:5432"
    networks:
      - lumen

  webserver:
    image: nginx:alpine
    container_name: lumen-webserver
    working_dir: /application
    volumes:
        - ./lumen:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - lumen
  php-fpm:
    build: phpdocker/php-fpm
    container_name: lumen-php-fpm
    working_dir: /application
    volumes:
      - ./lumen:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    networks:
      - lumen

networks:
  lumen:
    driver: bridge

